# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         pake
version:      0.21
version_from: pake
installdirs:  site
requires:
    Getopt::Std:                   1.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
